#!/bin/bash

# compress the files if they aren't
find web -iname '*.html' -size +100c -exec gzip -fk {} \;
find web -iname '*.htm' -size +100c -exec gzip -fk {} \;
find web -iname '*.js' -size +100c -exec gzip -fk {} \;
find web -iname '*.css' -size +100c -exec gzip -fk {} \;
find web -iname '*.woff' -size +100c -exec gzip -fk {} \;

#clean gziped directory and delete it
find gziped -iname '*' -exec rm {} \;
find gziped -iname '*' -exec rmdir -p {} \;

#create directory gziped
mkdir ./gziped

#create directory gziped_tmp
find web -type d | xargs -IZzZ mkdir -p gziped_tmp/ZzZ

#copy all .gz files with saving direcotry structure
find web -iname '*.gz' -exec cp -Rv {} gziped_tmp/{} \;
#remove all *.gz files from web
find web -iname '*.gz' -exec rm {} \;

mv gziped_tmp/web/* gziped

rmdir gziped_tmp/web
rmdir gziped_tmp

